services:
  - type: web
    name: bolt-diy
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm run dev
    envVars:
      - key: AI_PROVIDER
        value: openrouter
      - key: OPENROUTER_API_KEY
        value: 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
      - key: MODEL_NAME
        value: qwen/qwen-2.5-coder-32b-instruct:free
